{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kafka-backup-operator.serviceAccountName" . }}
  labels:
    {{- include "kafka-backup-operator.labels" . | nindent 4 }}
  annotations:
    {{- if and .Values.azureWorkloadIdentity.enabled .Values.azureWorkloadIdentity.clientId }}
    azure.workload.identity/client-id: {{ .Values.azureWorkloadIdentity.clientId | quote }}
    {{- end }}
    {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}
